// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reference.DotNetCore.AsyncApi.Context;

namespace Reference.DotNetCore.AsyncApi.Migrations
{
    [DbContext(typeof(NotesDbContext))]
    [Migration("20201121055250_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Reference.DotNetCore.AsyncApi.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ccc0814-0fc3-4d67-a5cd-b102a1871d7a"),
                            Content = "1. Dont't worry if it doesn't work right.If everything did, you'd be out of a job.",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.1. Dont't "
                        },
                        new
                        {
                            Id = new Guid("8bcde0c0-fe6d-49c3-bd4b-d48ff77b9c8d"),
                            Content = "2.  Don't comment bad code - rewrite it. - Brian Kernighan",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.2.  Don't "
                        },
                        new
                        {
                            Id = new Guid("570198b2-b1fc-4031-9133-bc3fd74e196d"),
                            Content = "3.  A programming language is for thinking about programs, not for expressing programs you've already thought of. It should be a pencil, not a pen. - Paul Graham",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.3.  A prog"
                        },
                        new
                        {
                            Id = new Guid("111f50c5-5b1f-456e-b606-15e601ab82c6"),
                            Content = "4.  Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday's code. - Dan Salomon",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.4.  Someti"
                        },
                        new
                        {
                            Id = new Guid("3a17ce48-dd5b-459d-b193-ca1717d5cb92"),
                            Content = "5.  It´s better to wait for a productive programmer to become available than it is to wait for the first available programmer to become productive. - Steve McConnell",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.5.  It´s b"
                        },
                        new
                        {
                            Id = new Guid("50876805-4725-45c5-8429-a43f5029edc4"),
                            Content = "6.  One of my most productive days was throwing away 1000 lines of code. Ken Thompson",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.6.  One of"
                        },
                        new
                        {
                            Id = new Guid("8887ea7b-db88-4137-8d3f-9bc189a75660"),
                            Content = "7.  Without requirements or design, programming is the art of adding bugs to an empty text file.",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.7.  Withou"
                        },
                        new
                        {
                            Id = new Guid("87fe3f21-7187-448b-a206-5505f41767fd"),
                            Content = "8.  One main'scrappy software is another man's full time job.",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.8.  One ma"
                        },
                        new
                        {
                            Id = new Guid("eafe745c-9704-4ab4-93ed-0443c1a7ddb1"),
                            Content = "9.  Walking on water and developing software from a specification are easy if both are frozen.",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.9.  Walkin"
                        },
                        new
                        {
                            Id = new Guid("d34a3291-6a9b-48cd-8a6f-3e457576e446"),
                            Content = "10.  Debugging is twice as hard as writing the code in the first place.Therfore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it. - Rajanand",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.10.  Debug"
                        },
                        new
                        {
                            Id = new Guid("4352c726-a5d5-4a98-a6e6-f97b1617e7be"),
                            Content = "11.  System programmers are the high priests of a low cult. - Robert S. Barton",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.11.  Syste"
                        },
                        new
                        {
                            Id = new Guid("940bbb94-b706-45b0-8584-1487e72728d6"),
                            Content = "12.  I don't care if it works on your machine! We are not shipping your machine! - Vidiu Platon",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.12.  I don"
                        },
                        new
                        {
                            Id = new Guid("35e7251d-7442-4d44-b075-8749b26184be"),
                            Content = "13.  Software undergoes beta testing shortly before iy' released.Beta is latin for \"still doesn't work\"",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.13.  Softw"
                        },
                        new
                        {
                            Id = new Guid("01209ed0-5453-4146-9338-8665eaf3deff"),
                            Content = "14.  Measuring programming progree by lines of code is like measuring aircraft building progree by weight. - Bill Gates",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.14.  Measu"
                        },
                        new
                        {
                            Id = new Guid("412bbc55-035f-4cea-add3-c994a9a095c9"),
                            Content = "15.  If debudding is the process of removing software bugs, then programming must be the process of putting them in. - Edsger W. Dijkstra",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.15.  If de"
                        },
                        new
                        {
                            Id = new Guid("31783669-7ef9-4099-8640-edb222b51f08"),
                            Content = "16.  The computer was born to solve problems that did not exist before. - Bill Gates",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.16.  The c"
                        },
                        new
                        {
                            Id = new Guid("16b5cb20-5b7f-4ac0-8cde-baa79a0c214d"),
                            Content = "17.  Real programmers don't comment their code. If it was hard to write, it should be hard to understand.",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.17.  Real "
                        },
                        new
                        {
                            Id = new Guid("0840cfda-f7b1-44a6-be7a-655c7e376949"),
                            Content = "18.  Always code as if the guy who ends up maintaning your code will be a violent psychopath who knows where you live. - Rick Osborne",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.18.  Alway"
                        },
                        new
                        {
                            Id = new Guid("98bc5cce-0fbe-4c84-bc28-2d845d9ab311"),
                            Content = "19.  People don't care about what you say, they care about what you build. - Mark Zuckerberg",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.19.  Peopl"
                        },
                        new
                        {
                            Id = new Guid("5f5a0a96-ccf2-495f-99bf-7c66d2969e5a"),
                            Content = "20.  We have to stop optimizing for programmers and start optimizing for users. — Jeff Atwood",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.20.  We ha"
                        },
                        new
                        {
                            Id = new Guid("5874696c-1ef8-4196-85b4-0c3e1d492975"),
                            Content = "21.  If the code and the comments do not match, possibly both are incorrect. — Norm Schryer",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.21.  If th"
                        },
                        new
                        {
                            Id = new Guid("2bb998b2-a720-4a8e-944f-ea5c996b7fa2"),
                            Content = "22.  Bad programmers worry about the code. Good programmers worry about data structures and their relationships. - Linus Torvalds",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.22.  Bad p"
                        },
                        new
                        {
                            Id = new Guid("c927fe17-9150-439c-ab96-1ae8af2d3e46"),
                            Content = "23.  If you optimize everything, you will always be unhappy. - Donald Knuth",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.23.  If yo"
                        },
                        new
                        {
                            Id = new Guid("59379e08-6204-404c-9099-78b73c23e183"),
                            Content = "24.  Your mind is programmable - if you're not programming your mind, else will program it for you. - Jeremy Hammond",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.24.  Your "
                        },
                        new
                        {
                            Id = new Guid("cf425147-47ee-42bb-9f27-e38728d1f184"),
                            Content = "25.  The trouble with programmers is that you can never tell what a programmer is doing until it's too late. - 	Seymour Cray",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.25.  The t"
                        },
                        new
                        {
                            Id = new Guid("3969aa68-0003-407b-ba7c-3b875468854e"),
                            Content = "26.  Debugging becomes significantly easier if you first admit that you are the problem. - William Laeder",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.26.  Debug"
                        },
                        new
                        {
                            Id = new Guid("ea7d8095-cc30-4d72-8e5c-e4c460f3fb9e"),
                            Content = "27.  Talk is cheap.Show me the code. - Linus Torvalds",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.27.  Talk "
                        },
                        new
                        {
                            Id = new Guid("4e2a3baf-cead-4cfb-ab17-400e51ea0364"),
                            Content = "28.  Everybody in this country should learn to program a computer because it teaches you how to think. - Steve Jobs",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.28.  Every"
                        },
                        new
                        {
                            Id = new Guid("a9a6e517-973f-4338-a667-a3fcf3899c81"),
                            Content = "29.  Most good programmers do programming not because they expect to get paid or get adulation by the public, but because it is fun to program. - Rajanand",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.29.  Most "
                        },
                        new
                        {
                            Id = new Guid("bb5619ad-6fe8-4406-b3eb-8286aaa7247c"),
                            Content = "30.  Any fool can write code that a computer can understand.Good programmers write code that humans can understand.",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.30.  Any f"
                        },
                        new
                        {
                            Id = new Guid("49a5b873-6f7f-4d5c-af8d-dc75fbc3a69d"),
                            Content = "31.  First, solve the problem.Then write the code. - John Johnson",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.31.  First"
                        },
                        new
                        {
                            Id = new Guid("87f8bd1e-4e2d-4e1b-ac2c-f745fcac8705"),
                            Content = "32.  The function of a good software is to make the complex appear to be simple. - Grady Booch",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.32.  The f"
                        },
                        new
                        {
                            Id = new Guid("253a1f3a-f119-4574-a637-a9401e4658f6"),
                            Content = "33.  Your most unhappy customers are your greatest source of learning. — Bill Gates",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.33.  Your "
                        },
                        new
                        {
                            Id = new Guid("04c3ef03-4118-43eb-805b-b6e8a7209353"),
                            Content = "34.  Small minds are concerned with the extraordinary, great minds with the ordinary. - Blaise Pascal",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.34.  Small"
                        },
                        new
                        {
                            Id = new Guid("a8730c6e-980a-4e2b-b0ee-2051277f5f40"),
                            Content = "35.  Everyday life is like programming, I guess.If you love something you can put beauty on it. - Donald Knuth",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.35.  Every"
                        },
                        new
                        {
                            Id = new Guid("aca4cb83-6d3f-4a8c-b0d9-bd071ecce187"),
                            Content = "36.  You are not responsible for the programming you picked up in childhood.However, as an adult, you are the one hundred percent responsible for fixing it.",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.36.  You a"
                        },
                        new
                        {
                            Id = new Guid("768e15a1-db0e-404a-b78a-ede6b05e1e69"),
                            Content = "37.  Developer is an organism that turns coffee into code.",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.37.  Devel"
                        },
                        new
                        {
                            Id = new Guid("c529130f-484e-4eaa-8e09-3b081c824b96"),
                            Content = "38.  The purpose of software engineering is to control complexity, not to create it.",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.38.  The p"
                        },
                        new
                        {
                            Id = new Guid("729c351d-5256-4f71-bdb8-0895efca0725"),
                            Content = "39.  As a programmer, it is your job to put yourself out of business. What you do today can be automated tomorrow. - Doug McIlroy",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.39.  As a "
                        },
                        new
                        {
                            Id = new Guid("fd71afc6-ec17-474a-8802-0ef9ce9676f5"),
                            Content = "40.  A good programmer is someone who always looks both ways before crossing a one-way street. - Doug Linder",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.40.  A goo"
                        },
                        new
                        {
                            Id = new Guid("68a83d18-d005-42e9-8e3b-843a984e1fdd"),
                            Content = "41.  Testing can only prove the presence of bugs, not their absence. – Edsger W. Dijkstra",
                            DateCreated = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            DateLastModified = new DateTime(2020, 11, 21, 0, 52, 50, 222, DateTimeKind.Local).AddTicks(80),
                            Title = "20201121125250.41.  Testi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
